# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6a5915ad29a0a153be168792efeb2467ebe5fa0e1e3b56f3394913966efdaf5ceb42e063e0b233d0ccd64f700123602a0605770dd1eed4500904cc2a8861e410

test:
  secret_key_base: 0ce01e2faf7b5003e2f2af657953823cbcced83c792dac23c1645842c9155d8520fa1b4e9b4c134cb8ab0a8a41a405f0ea91e1aeea9d17f82ce4afa93b00afde

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
